name: deploy

on:
  workflow_dispatch:
  push:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: change permission
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/jwp-shopping-order 
      - uses: actions/checkout@v3

      - name: Copy secrets.env
        run:
          echo "MYSQL_URL={{ secrets.MYSQL_URL }}" >> src/main/resources/secrets.env
          echo "MYSQL_USERNAME={{ secrets.MYSQL_USERNAME }}" >> src/main/resources/secrets.env
          echo "MYSQL_PASSWORD={{ secrets.MYSQL_PASSWORD }}" >> src/main/resources/secrets.env
          cat src/main/resources/secrets.env

      - name: gradle bootjar
        run: |
          chmod +x ./gradlew
          ./gradlew bootjar

      - name: kill 8080 port if exist
        run: |
          if sudo lsof -i :8080; then
            echo "Port 8080 is already in use. Killing the process..."
            sudo lsof -i :8080 | awk 'NR!=1 {print $2}' | sudo xargs kill -9
          fi

      - name: deploy
        run: |
          env
          sudo java -jar build/libs/jwp-shopping-order.jar --spring.profiles.active=prod &
